# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$kubernetes $aws $python
$directory $git_branch
$character
'''

# Inserts a blank line between shell prompts
add_newline = false

# https://starship.rs/config/#package-version
[package]
disabled = true

# https://starship.rs/config/#aws
[aws]
format = '| [$symbol($profile)]($style)'

# https://starship.rs/config/#git-branch
[git_branch]
symbol = "ğŸ”€ "
format = "| [$symbol$branch]($style) "

# https://starship.rs/config/#python
[python]
symbol = 'ğŸ '
style = 'green'
format = "| [$virtualenv]($style)"

# https://starship.rs/config/#character
[character]
success_symbol = '[\$](bold black)'
error_symbol = '[\$](bold black)'

# https://starship.rs/config/#kubernetes
[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
contexts = [
  { context_pattern = "*kind*", style = "blue", symbol = "ğŸ“š " },
  { context_pattern = "*rancher-desktop*", style = "blue", symbol = "ğŸ“š " },
  # { context_pattern = "other*", style = "blue", symbol = "ğŸ”µ " },
  { context_pattern = "dev-a", style = "yellow", symbol = "ğŸŸ¡ " },
  { context_pattern = "dev-a.whoop.com", style = "yellow", symbol = "ğŸŸ¡ " },
  { context_pattern = "prod-a", style = "red", symbol = "ğŸ”´ " },
  { context_pattern = "prod-a.whoop.com", style = "red", symbol = "ğŸ”´ " },
]

# https://starship.rs/config/#directory
[directory]
style = 'white'
truncate_to_repo = false
truncation_length = 0